// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALLXp7C53hq05uvPwm93AbRcjtMlTnNMo',
    appId: '1:937013338746:web:09518a45a56d956d98d1c3',
    messagingSenderId: '937013338746',
    projectId: 'mini-project-63a88',
    authDomain: 'mini-project-63a88.firebaseapp.com',
    storageBucket: 'mini-project-63a88.appspot.com',
    measurementId: 'G-J47Z46B6KV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDV_LNJY2RXHPzay_FoSbPMcK2mLuyj2Rg',
    appId: '1:937013338746:android:295ab66d2c1802bb98d1c3',
    messagingSenderId: '937013338746',
    projectId: 'mini-project-63a88',
    storageBucket: 'mini-project-63a88.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaZ9On0RtG9uqphT5z0ivwOLA7NMVw8ME',
    appId: '1:937013338746:ios:43fb5aad510a77b098d1c3',
    messagingSenderId: '937013338746',
    projectId: 'mini-project-63a88',
    storageBucket: 'mini-project-63a88.appspot.com',
    iosClientId: '937013338746-t6rp70l7r0kqi065n63fk0u4cfjk4fa5.apps.googleusercontent.com',
    iosBundleId: 'com.example.miniProjet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDaZ9On0RtG9uqphT5z0ivwOLA7NMVw8ME',
    appId: '1:937013338746:ios:fc127478c9e0ec4898d1c3',
    messagingSenderId: '937013338746',
    projectId: 'mini-project-63a88',
    storageBucket: 'mini-project-63a88.appspot.com',
    iosClientId: '937013338746-a9norf0hhs7if6tec3omk399pbbqhsj8.apps.googleusercontent.com',
    iosBundleId: 'com.example.miniProjet.RunnerTests',
  );
}
